Demo5/Controllers/IssueController.cs
using Demo5.Models;
using IssueTracker.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace IssueTracker.Controllers
{
    [Authorize]
    public class IssueController : Controller
    {

        public readonly DBContextSample _dBContextSample;
     



        public IssueController(DBContextSample dBContextSample)
        {
            _dBContextSample = dBContextSample;
           
            
        }


        public IActionResult Index()
        {
            
            var loggedInUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            
            if (User.IsInRole("Admin"))
            {
                
                var objIssuesList = _dBContextSample.Issues
                    .Include(issue => issue.CreatedBy)
                    .Include(issue => issue.Project)
                    .ToList();

                return View(objIssuesList);
            }
            else if (User.IsInRole("Customer"))
            {
                if (_dBContextSample.Permissions !=null)
                {
                    var permittedProjectIds = _dBContextSample.Permissions
                  .Where(permission => permission.User.Id == loggedInUserId)
                  .Select(permission => permission.Project.Id)
                  .ToList();


                    var objIssuesList = _dBContextSample.Issues
                        .Include(issue => issue.CreatedBy)
                        .Include(issue => issue.Project)
                        .Where(issue => permittedProjectIds.Contains(issue.Project.Id))
                        .ToList();

                    return View(objIssuesList);
                }
                else
                {

                    return View(null);
                }
                   
              
               

                
            }

            
            return RedirectToAction("Error");
        }


        //GET
        public IActionResult Create()
        {
            var loggedInUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

           
            if (User.IsInRole("Customer"))
            {
                
                var permittedProjectIds = _dBContextSample.Permissions
                    .Where(permission => permission.User.Id == loggedInUserId)
                    .Select(permission => permission.Project.Id)
                    .ToList();

                var permittedProjects = _dBContextSample.Projects
                    .Where(project => permittedProjectIds.Contains(project.Id))
                    .ToList();

                var projectListItems = permittedProjects.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }).ToList();

                ViewData["Projects"] = projectListItems;

                return View();
            }
            else
            {
                
                var projects = _dBContextSample.Projects.ToList();
                var projectListItems = projects.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }).ToList();
                ViewData["Projects"] = projectListItems;

                return View();
            }
        }



        //POST
        [HttpPost]
        public IActionResult Create(Issue obj)
        {
            var selectedProjectId = obj.ProjectId;
            var selectedProject = _dBContextSample.Projects
                .Include(p => p.Issues)
                .FirstOrDefault(p => p.Id == selectedProjectId);

            selectedProject.Issues.Add(obj);

            var loggedInUserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (!string.IsNullOrEmpty(loggedInUserId))
            {
                var loggedInUser = _dBContextSample.Users.FirstOrDefault(u => u.Id == loggedInUserId);

                if (loggedInUser != null)
                {
                    obj.CreatedBy = loggedInUser;
                }
            }

            obj.CreatedDate = DateTime.Now;
            obj.Status = IssueStatus.Opened; 

            _dBContextSample.Issues.Add(obj);
            _dBContextSample.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult IssueDetail(Guid id)
        {
            var issue = _dBContextSample.Issues
    .Include(i => i.CreatedBy)
    .Include(i => i.Comments)
        .ThenInclude(c => c.CreatedBy) // Yorumların yaratıcılarını Include etmek için
    .FirstOrDefault(i => i.Id == id);




            if (issue == null)
            {
                
                return RedirectToAction("Error");
            }
         

            return View(issue);
        }


        [HttpPost]
        public IActionResult EditIssueText(Guid issueId, string issueText)
        {
            var issue = _dBContextSample.Issues.FirstOrDefault(c => c.Id == issueId);

            if (issue == null)
            {
                return NotFound();
            }

            issue.Description = issueText;
            _dBContextSample.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult DeleteIssue(Guid issueId)
        {
           
            var issue = _dBContextSample.Issues.FirstOrDefault(c => c.Id == issueId);

            if (issue != null)
            {
                _dBContextSample.Issues.Remove(issue);
                _dBContextSample.SaveChanges();
            }

            return RedirectToAction("Index");
        }








    }
}

Demo5/Controllers/PermissionsController.cs
using Demo5.Models;
using IssueTracker.DataAccess.Data;
using IssueTracker.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IssueTracker.Controllers
{
    public class PermissionsController : Controller
    {
        public readonly DBContextSample _dBContextSample;

  


        public PermissionsController(DBContextSample dBContextSample)
        {
            _dBContextSample = dBContextSample;
        }
        public IActionResult Index()
        {
            var permissionsList= _dBContextSample.Permissions;
            var users = _dBContextSample.Users.Where(p => p.isDeleted==false).ToList();
            var projects = _dBContextSample.Projects.ToList();



            var viewModel = new PermissionsViewModel();
            foreach (var item in projects)
            {
               viewModel.Projectnames.Add(item.Name);
               
            }
            foreach (var item in users)
            {
                viewModel.Usernames.Add(item.UserName);
            }
            if(permissionsList!=null)
            {
                viewModel.Permissions = permissionsList.ToList();
            }

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(string username, string projectname)
        {
            var user = _dBContextSample.Users.Where(i => i.Email == username).FirstOrDefault();
            var project = _dBContextSample.Projects.Where(i => i.Name == projectname).FirstOrDefault();

            if (user != null && project != null)
            {
                
                var existingPermission = _dBContextSample.Permissions.FirstOrDefault(p => p.User == user && p.Project == project);
                if (existingPermission == null)
                {
                    var newPermission = new Permissions() { User = user, Project = project };
                    
                    _dBContextSample.Permissions.Add(newPermission);
                    _dBContextSample.SaveChanges();
                }
               

               
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            var permission = _dBContextSample.Permissions.FirstOrDefault(p => p.Id == id);

            if (permission != null)
            {
                _dBContextSample.Permissions.Remove(permission);
                _dBContextSample.SaveChanges();
            }

            return RedirectToAction("Index");
        }






    }
}

Demo5/Controllers/ProjectController.cs
using IssueTracker.Areas.Identity.Data;
using Demo5.Models;
using IssueTracker.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Demo5.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {

        public readonly DBContextSample _dBContextSample;


        public ProjectController(DBContextSample dBContextSample)
        {
            _dBContextSample = dBContextSample;
        }
        public IActionResult Index()
        {
            var user = _dBContextSample.Users.FirstOrDefault(u => u.Email == User.Identity.Name);

            IEnumerable<Project> objProjectsList;
            if (User.IsInRole("Admin"))
            {
                
                objProjectsList = _dBContextSample.Projects;
            }
            else if (User.IsInRole("Customer"))
            {
                
                var userProjects = _dBContextSample.Permissions
                    .Where(p => p.User == user)
                    .Select(p => p.Project)
                    .ToList();

                objProjectsList = userProjects;
            }
            else
            {
               
                objProjectsList = new List<Project>();
            }

            return View(objProjectsList);
        }



        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {


            return View();
        }

        [HttpPost]
        public IActionResult Create(Project obj)
        {


            
            Guid projectId = Guid.NewGuid();

         
            obj.Id = projectId;

           
            obj.Issues=new List<Issue>();

            _dBContextSample.Projects.Add(obj);
            _dBContextSample.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            
            var projectToDelete = _dBContextSample.Projects.FirstOrDefault(p => p.Id == id);

            if (projectToDelete != null)
            {
                
                _dBContextSample.Projects.Remove(projectToDelete);
                _dBContextSample.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult ProjectIssueList(Guid id)
        {
            var projectId = id.ToString().ToLower();

            var project = _dBContextSample.Projects
                .Include(p => p.Issues) 
                .FirstOrDefault(p => p.Id.ToString().ToLower() == projectId);

            if (project != null)
            {
                var projectIssueList = project.Issues;
                return View(projectIssueList);
            }

            
            return RedirectToAction("Error");


        }

    }
}

Demo5/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using IssueTracker.Areas.Identity.Data
@inject SignInManager<SampleUser> SignInManager
@inject UserManager<SampleUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo5</title>
    <link rel="stylesheet" href="~/css/bootswathTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo5.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    
</head>
<body >
    @if (User.Identity.IsAuthenticated)
    {
        <header>

            <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Issue Tracker</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Index">Issues</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Permissions" asp-action="Index">Permissions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                                </li>
                            }

                        
                        
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>

                    <partial name="_LoginPartial" />
                </div>
            </div>

        </nav>
        
    </header>
    }
    
    
    
    <div class="container-fluid">
        <div class="row">
            
            <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <i class="bi bi-exclamation-circle"></i>
                                Issues
                                
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Sidebar Öğe 2
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Sidebar Öğe 1
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Sidebar Öğe 2
                            </a>
                        </li>
                      
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>